AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/${AppId}-${AWS::Region}-PermissionsBoundary'

Parameters:
  AppId:
    Type: String

Resources:
  sqsPayloadLoggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
      Runtime: nodejs10.x
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      MemorySize: 128
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
      Policies:
        # Give Lambda basic execution Permission to the sqsPayloadLogger
        - AWSLambdaBasicExecutionRole
      Events:
        SimpleQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
  SimpleQueue:
    Type: AWS::SQS::Queue
